### PR TITLE
Rethink `rt file`

### PR DESCRIPTION
**Pull request by JosiahParry**
Here is a PR to your PR that rethinks how `rt file` can be implemented.

Rather than searching for the package, we can make a informed guess as to where it is located. Additionally, this provides the option to run `testthat::test_file()` _without_ loading an R package. 

At a previous role we used testthat to run our tests for production code that was outside of the context of an R package. This would've helped.

New help

```
⚡ rt file --help
Usage: rt file [<file>] [-P <pkg-dir>] [-s]

Test a single file using testthat

Positional Arguments:
  file              path to a test file

Options:
  -P, --pkg-dir     path to the package (default `.`)
  -s, --standalone  do not load the development package
  --help            display usage information
```

## test file from pkg root

```
⚡ rt file tests/testthat/test-arc-base-req.R
ℹ Loading arcgisutils

══ Testing test-arc-base-req.R ═══════════════════════════════════════════════════════════
[ FAIL 0 | WARN 0 | SKIP 0 | PASS 4 ] Done!
rt exited :)
```

## test file from pkg tests folder 

```
tests ⚡ rt file tests/testthat/test-arc-base-req.R
ℹ Loading arcgisutils
Error: `path` does not exist
Execution halted
The rt subprocess exited with an error: ExitStatus(unix_wait_status(256))
```

This doesn't work because that path doesnt exist. But if we remove the prefixed `tests` devtools is smart enough to know we're still in a package.

```
tests ⚡ rt file testthat/test-arc-base-req.R
ℹ Loading arcgisutils

══ Testing test-arc-base-req.R ═══════════════════════════════════════════════════════════
[ FAIL 0 | WARN 0 | SKIP 0 | PASS 4 ] Done!
rt exited :)
```

## running in standalone mode

Standalone mode will run a test without loading an R package. We expect it to fail here. 

```
⚡ rt file testthat/test-arc-base-req.R -s

══ Testing test-arc-base-req.R ═══════════════════════════════════════════════════════════
[ FAIL 4 | WARN 0 | SKIP 0 | PASS 0 ]

── Error (test-arc-base-req.R:2:3): agent is arcgisutils ───────────────────────
Error in `arc_base_req("http://google.com")`: could not find function "arc_base_req"

── Error (test-arc-base-req.R:14:3): token is added as header ──────────────────
Error in `arc_host()`: could not find function "arc_host"
Backtrace:
    ▆
 1. └─httr2::oauth_token(token_value, arcgis_host = arc_host()) at test-arc-base-req.R:14:3
 2.   ├─base::structure(...)
 3.   ├─httr2:::compact(...)
 4.   │ └─base::Filter(length, .x)
 5.   │   ├─base::unlist(lapply(x, f))
 6.   │   └─base::lapply(x, f)
 7.   └─rlang::list2(...)

── Error (test-arc-base-req.R:32:3): path is appended ──────────────────────────
Error in `arc_base_req("http://google.com", path = path_vals)`: could not find function "arc_base_req"

── Error (test-arc-base-req.R:52:3): query is appended ─────────────────────────
Error in `arc_base_req("http://google.com", query = query)`: could not find function "arc_base_req"
[ FAIL 4 | WARN 0 | SKIP 0 | PASS 0 ]
rt exited :)
```

But if I run the package's `tests/testthat.R` file this works because it loads the R package.

```
⚡ rt file testthat.R -s

. . . truncated . . .
══ Skipped tests (4) ═════════════════════════════════════════════════════════════════════
• must be done interactively (1): test-fetch_layer_metadata.R:26:3
• On CRAN (1): test-date-parsing.R:6:3
• Skipping (2): test-fetch_layer_metadata.R:2:3, test-fetch_layer_metadata.R:13:3

[ FAIL 0 | WARN 0 | SKIP 4 | PASS 27 ]
 Done!
rt exited :)
```

### CODE REVIEW

**Comment by sckott** [comment]
sweet, I'll have a look in a bit ...

**Comment by sckott** [comment]
> without loading an R package

How exactly does that work?  

So does `-s` only work if you run I like `rt file testthat.R -s`?

This mostly seems good, though I'm not sure I follow `rt file testthat.R -s`  in the sense that doesn't that run all tests? The idea with `rt file` at least for me is that you can test 1 or more files rather than all tests. But maybe I'm misunderstanding?

**Comment by JosiahParry** [comment]
The `--standalone` option does not run `devtools::load_all()` it only calls `testthat::test_file()`. 

This allows people to use this cli outside of the context of package development. `{testthat}` has utility outside of package unit tests and I think it is nice to support that as well :)

**Comment by sckott** [comment]
Got it, okay, makes sense on the standalone use case. 

This does make more sense, merging.

**Pull request merged**
