### PR TITLE
bug: provide informative message when no tests are found rt-list

### LINKED ISSUE #5: Commands dir, file list: fail well when not inside a package
Right now we do give useful info but could print a simpler (e.g., one liner) message

```
# not in a R pkg
rt dir .
```

```
Error in `package_file()`:
! Could not find package root.
ℹ Is . inside a package?
Backtrace:
    ▆
 1. └─devtools::test(".")
 2.   └─devtools::as.package(pkg)
 3.     └─devtools::package_file(path = x)
 4.       └─cli::cli_abort(c("Could not find package root.", i = "Is {.path {base_path}} inside a package?"))
 5.         └─rlang::abort(...)
Execution halted
The rt subprocess exited with an error: ExitStatus(unix_wait_status(256))
```

`rt list` just doesn't return anything - which maybe is fine but ideally these 3 commands behave the same

### PR DESCRIPTION
**Pull request by JosiahParry**
This PR closes #5 by adding a message when no tests are found. 

I also changed the variant names for the enum to make it easier to follow. 

I was also playing around with emojis here. Can remove :)

### CODE REVIEW

**Comment by JosiahParry** [comment]
Running from `rt-cli` I get 

```
rt-cli ⚡ rt list
❗️ No tests found.
```

Running with a path to a package with tests: 

```
rt-cli ⚡ rt list ../../../arcgisutils
Found 9 tests
📌 ../../../arcgisutils/tests/testthat/test-arc-base-req.R
📌 ../../../arcgisutils/tests/testthat/test-arc_token.R
📌 ../../../arcgisutils/tests/testthat/test-date-handling.R
📌 ../../../arcgisutils/tests/testthat/test-date-parsing.R
📌 ../../../arcgisutils/tests/testthat/test-empty-results.R
📌 ../../../arcgisutils/tests/testthat/test-fetch_layer_metadata.R
📌 ../../../arcgisutils/tests/testthat/test-json-conversions.R
📌 ../../../arcgisutils/tests/testthat/test-null-geometry.R
📌 ../../../arcgisutils/tests/testthat/test-rbind-results.R
```

**Comment by sckott** [comment]
> changed the variant names for the enum to make it easier to follow.

sounds good 👍🏽 

This takes care of `list` nicely! Is it straightforward to take care of `dir` and `file` too? If not, we can do that later. 

I'm on the fence regarding the push pin emoji. I'm generally pro emoji but I I think using the same emoji repeatedly isn't my preference

**Comment by JosiahParry** [comment]
I've gone ahead and removed the pin—i too felt it was obnoxious.

Modifying `dir` and `file` is less simple because the error message is emitted from R and not Rust.

**Comment by sckott** [comment]
> Modifying dir and file is less simple because the error message is emitted from R and not Rust.

okay, I'll keep #5 open then

**Pull request merged**
